from hibp import HIBP
import requests
import gevent
import time
import json

emails = ['DAVIDEDWARDS44@YAHOO.COM',
'KIMBARTON00@COMCAST.NET',
'trista_caldwell@comcast.com',
'thernandez219@gmail.com',
'stefanbekker@mac.com',
's.jozwiak@comcast.net',
'scuba_steve18@yahoo.com',
'MICHELLE.LETO@GMAIL.COM',
'marvivey@comcast.net',
'juliafrank21@gmail.com',
'horse.aries@hotmail.com',
'dhlh1291@outlook.com',
'chasedreamz78@gmail.com',
'beccaleannpaxton@gmail.com',
'bayrocanady@me.com',
'ztk0702@gmail.com',
'zlotoffpaul@yahoo.com',
'zakmohsen@aol.com',
'yordty@gmail.com',
'ymsslzr@gmail.com',
'xoanvagner@gmail.com',
'xhusbands86@gmail.com',
'windandrain1@yahoo.com',
'WELOVEYOU832@COMCAST.NET',
'wejudy@aol.com',
'vinaygunnam85@gmail.com',
'tycooper317@yahoo.com',
'ttleague@comcast.net',
'trvoribrndt@gmail.com',
'tru.mubri.20@gmail.com',
'TONYTREVINO222@GMAIL.COM',
'tishsullivan6@aol.com',
'terrazasb@icloud.com',
'TBROWN231121@COMCAST.NET',
'tankdogg0403@gmail.com',
'tanishahurdle1@gmail.com',
'sychu@yahoo.com',
'sweeti0521@aol.com',
'swedakabst@yahoo.com',
'STILLBEAUTY@ME.COM',
'squirrelranch.jf@gmail.com',
'spalmeri1961@yahoo.com',
'sinoplj@comcast.net',
'shelleyrichards@sbcglobal.net',
'sharonrharrison@gmail.com',
'shaobo_w@hotmail.com',
'seidy1983@aol.com',
'seanoconnor900@outlook.com',
'scat7s@comcast.net',
'sbou_92@yahoo.com',
'sasmith782009@yahoo.com',
'sandrayeater@comcast.net',
'SANDERS10245@COMCAST.NET',
'sammie_jai@icloud.com',
'rwinston3545@yahoo.com',
'rosario.gordillo@gmail.com',
'ron.machamer@comcast.net',
'romeocaampued@gmail.com',
'robertsklotz@gmail.com',
'rnas87@yahoo.com',
'ripjoshbeal@comcast.net',
'rinmiurha@gmail.com',
'ricorosa1225@gmail.com',
'raydedavis@gmail.com',
'ravenfesta20@gmail.com',
'rahulmaniktala@gmail.com',
'priscillar79@gmail.com',
'prakashpoonam93@gmail.com',
'poo.rad.am.77@gmail.com',
'poill1980@rhyta.com',
'pmmckillop@aol.com',
'platinu.mtransportsolutions2010@gmail.com',
'petsamone@yahoo.com',
'pennsyl.vania101383philadelphia@gmail.com',
'penelopesk@yahoo.com',
'nhoonsbeen@comcast.net',
'nemiyah117@gmail.com',
'NELLIEO25@GMAIL.COM',
'nekirk@aol.com',
'naturall721@gmail.com',
'nathankdevos@comcast.net',
'mz9761@comcast.net',
'msnyder007@sutiami.gq',
'mrfixit15301@yahoo.com',
'moverandshaker08@icloud.com',
'Modesto344793@comcast.net',
'mmagruder12@gmail.com',
'miguelzamora756@gmail.com',
'memcc@comcast.net',
'medeirosmf@comcast.net',
'mbowen01@gmail.com',
'martinmills@outlook.com',
'marks71camaro71@gmail.com',
'margiesellers@icloud.com',
'MARCOPALOMO1992@COMCAST.NET',
'lovey.oursapparently19.88@gmail.com',
'lisasenters@hotmail.com',
'lisadgravier1@gmail.com',
'lexiegurl@gmail.com',
'lakrader@comcast.net',
'laken299@yahoo.com',
'kymb1968@yahoo.com',
'KSHANENA@YAHOO.COM',
'krupa33@comcast.net',
'kmcmlc@att.net',
'kilojohnson0509@gmail.com',
'jrpalladina@gmail.com',
'JON.GLAZE@ALLEGION.COM',
'jmille20@gmail.com',
'jmccune3986@gmail.com',
'jlsaune23@msn.com',
'jk105bn@comcast.net',
'jgetsmart810@gmail.com',
'jgerbi@gmail.com',
'jfelt801@gmail.com',
'jesuphia25@yahoo.com',
'jelinadadaf.a@gmail.com',
'jeffvitek@sbcglobal.net',
'javonabney92@yahoo.com',
'janiene.friend@comcast.net',
'james.patric.k0071@gmail.com',
'james.larimore@gmail.com',
'JAIMES.DRAM872@GMAIL.COM']

breach_list = []
pwned = []

for email in emails:

	req = HIBP.get_account_breaches(email)
	req.execute()
	if req.response == 'object has not been pwned.':
		pass
	else:
		print(json.dumps(req.response, indent=4, sort_keys=True))
		pwned.append(email)
		for item in req.response:
			breach_list.append(item['Domain'])
	time.sleep(1.3)

print(breach_list)
print('Total UIDs pwned: %s' % len(pwned))